### ISSUE TITLE
what is missing for comfortable use

### ISSUE THREAD

**Issue by hikikomori4** [cmus/cmus#1122]
since the author (or one of the authors) is russian-speaking, I will allow myself to write in my native language and copy in english. I apologize if anyone is uncomfortable this. 

RUS: Перешёл пользоваться cmus, так как очень люблю vim-like. Есть несколько пожеланий, которы я оформил ниже.
ENG: I switched to using cmus, because I really love vim-like. There are several wishes that I have issued below. 

* * *

RUS: 
НЕПОЛНОЦЕННОСТЬ ВИДОВ 2,3
В режиме отображения Sorted library view (2) и playlist (3) не показывается тэг album. Только artist и name. Невозможно понять, из какого альбома песня.  В Режиме Library view (1) отображается.
Это не позволяет полноценно использовать какие-либо режимы, кроме 1го, только в дополнение.

ENG:
INSUFFICIENCY OF views 2,3
The `album` tag is not shown in the `Sorted library` view (2) and `playlist` (3) display mode. Only `artist` and `name` tags. It is impossible to know which `album` tag of the song. In Library view (1) is displayed. This does not allow you to fully use any modes, except for the 1st, only in addition.

* * *
RUS:
ПРОГРЕССБАР У ВОСПРОИЗВОДИМОГО ТРЕКА
Неудобно считывать положение в треке из цифр - 00:14 / 01:50 . Для музыкального плеера очень не хватает такой основной части, как прогрессбар. Библиотека ncurses явно что-то такое умеет:  [██████████████55%█░░░░░░░░░░░░░░░░]
Не хватает запоминания позиции воспроизведения set resume=true ПО УМОЛЧАНИЮ после выхода из программы при прослушивании аудиокниг.

ENG:
PLAYBACK POSITION INDICATOR BY PROGRESSBAR
Displaying the playback position in numbers (00:14 / 01:50) is not sufficient.
For easy reading of the playback position, the progress bar is more logical. The ncurses library does this: [██████████████55% █░░░░░░░░░░░░░░░░]
The "resume = true" setting should be set to "True" by default. The reason is the continuation of playback after exiting the program while listening to audiobooks. 

* * *
RUS:
ЭКВАЛАЙЗЕР
Не хватает графического эквалайзера для визуализации звука. Это не только украшательство, так я вижу что звук есть и какого он уровня, когда управляю cmus по ssh на удалённой машине, которую я не слышу.
Пока спасаюсь тем, что запускаю в сеанс tmux cmus и cava.

ENG:
EQUALIZER
There is not enough BUILT-IN graphic equalizer for sound rendering. This is not only a decoration, so I see that there is sound and what level it is when I control cmus via ssh on a remote machine, which I cannot hear.
So far I am saving myself by running cmus and cava in the tmux session.
* * *

RUS: 
ПОЛОСА ПРОКРУТКИ
Vim style и всё такое, но не хватает вертикальных полос прокрутки в библиотеках. Когда музыки много, невозможно понять в каком % рулона списка находишься. Косвенный признак - алфавитная сортировка, но когда несколько сотен треков начинаются на одну букву, то это не работает.

ENG:
SCROLL BAR
The Vim style is cool, but the lack of vertical scrollbars in the libraries is disorienting. When there is a lot of music, it is impossible to understand where the cursor position is in the list. An indirect sign is alphabetical sorting, but when several hundred tracks start with one letter, this does not work. 

* * *

RUS:
MUSIC TAG VIEW & EDIT
Удивительно, что этого нет, не хватает просмотрщика и редактора всех тэгов трека(треков). Нет возможности увидеть на одном экране все тэги трека, его путь и имя файла. Учитывая, что далеко не все треки бывают заполнены правильно и появляется зверинец с тэгами, оперативно внутри программы это посмотреть и исправить возможности нет.

ENG:
MUSIC TAG VIEW & EDIT
Surprisingly, this is not the case, there is not enough viewer and editor for all ID3Tags tracks. There is no way to see all the tags of a track, its path and file name on one screen. Considering that not all tracks are filled in correctly and a menagerie with tags appears, there is no way to see and fix it quickly inside the program. 

* * *

RUS: 
ВКЛАДКИ
Треки сперва добавляются в базу ~/.config/cmus/lib.pl, и уже затем cmus с нею работает. Почему бы в случае отсутствующего трека просто не предлагать его поискать по имеющимся путям? Скорее всего его просто переименовали,зачем осложнять жизнь нудным ручным добавлением?
Также очень отвлекает одна большая помойка БД на всю программу. Либо у меня всё в куче, либо каждый раз приходится прыгать по папкам и добавлять нужных исполнителей, мучиться с плейлистами и их поддержкой в актуальном виде.
Хотелось бы поддержки вкладок, чтобы музыка была у меня в одном месте, аудиокниги в другом, всякий хлам в третьем. И всё доступно мгновенно, а не путём :clear :add path/folder. Вкладки это простое и удобное решение!

ENG:
TABS SUPPORT
Tracks are first added to the "~/.config/cmus/lib.pl" database, and only then cmus works with it. Why not, in the case of a missing track, simply offer to search for it along the available paths? Most likely it was simply renamed, why complicate life with a tedious manual addition?
It is also very distracting one big dump of the database for the whole program. Either I have everything in a heap, or every time I have to jump through folders and add the necessary artists, struggle with playlists and their support in an up-to-date form.
I would like to have tab support, so that I have music in one place, audiobooks in another, all trash in the third. And everything is available instantly, and not by: clear: add path / folder. Tabs are a simple and convenient solution! 

* * *

RUS:
КОДИРОВКА ПО УМОЛЧАНИЮ
Почему бы не проверять при старте язык системы, и если например: LANG=ru_RU.UTF-8, LANGUAGE=ru, то назначать переменную id3_default_charset=cp1251 исключая проблемы с кодировкой у пользователя? Это ещё хорошо, что я вручную нашёл решение, как корректно отображать тэги в 1251, но убил кучу времени, наблюдая кучу кракозябр в списках воспроизведения.

ENG:
DEFAULT CODEPAGE
Why not check the system language at startup, and if, for example: LANG=ru_RU.UTF-8, LANGUAGE=ru, then assign the id3_default_charset = cp1251 variable, excluding user coding problems? It's also good that I manually figured out how to display tags correctly in 1251, but wasted a lot of time seeing a bunch of cracks in playlists. 

* * *
Thank you for reading! I hope my thoughts will resonate in the minds of respected developers. Thanks for the great software, we will make it better! 
* * *

---

1) `uname -a`: 
```
(Linux 4.19.207-1-MANJARO #1 SMP Wed Sep 22 12:34:06 UTC 2021 x86_64 GNU/Linux)
```

2) `cmus --version`:
```
cmus v2.9.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors

```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao

```

**Comment by gunqqer** [comment]
Translation via deepl.com:
I am using cmus because I like vim-like. There are a few requests, which I've summarized below.

THE INCOMPLETENESS OF VIEWS 2,3
In Sorted library view (2) and playlist (3) do not show the album tag. Only artist and name. It is impossible to understand which album the song is from. In Library view (1) it is displayed.
This does not allow to fully use any modes except the 1st, only in addition.

THE PROGRESS BAR OF THE TRACK BEING PLAYED.
It is inconvenient to read the position in the track from the numbers - 00:14 / 01:50 . For a music player, a basic part like the progress bar is very lacking. The ncurses library obviously can do something like that: [""""""""""""""55%"░░░░░░░░░░░░░░░░]
What's missing is the memory of the playback position by DETERMINATION after exiting the program when listening to audiobooks.

EQUALIZER
There is not enough graphic equalizer to visualize the sound. It's not just a decoration, I can see what sound is there and what level it is when I run cmus via ssh on a remote machine which I can't hear.
So far I save myself by running cmus and cava in a tmux session.

SCROLLBAR.
Vim style and all, but not enough vertical scrollbars in libraries. When there's a lot of music, you can't tell what % of the list roll you're in. Alphabetical sorting is indirect, but when several hundred tracks start with one letter, it doesn't work.

MUSIC TAG VIEW & EDIT
Surprisingly this is not available, there is no viewer and editor for all the track(s) tags. There is no possibility to see all the track's tags, its path and file name on one screen. Given that not all the tracks are not filled correctly and appears menagerie of tags, quickly within the program to look at it and fix it is not possible.

ENTERTAINMENTS
The tracks are added to the ~/.config/cmus/lib.pl database first, and then cmus works with it. Why in case of a missing track don't you suggest to search for it by existing paths? Most likely it was just renamed, why complicate life with tedious manual addition?

Also very distracting is one big dump of database for the whole program. Either I have everything in a pile, or every time I have to jump through folders and add the right artists, agonize with playlists and keeping them up to date.
I'd like tab support so I have music in one place, audiobooks in another, junk in a third. And everything is available instantly, not by :clear :add path/folder. Tabs are a simple and convenient solution!

DEFAULT ENCODING.
Why not check at startup the system language and if for example: LANG=en_U.UTF-8, LANGUAGE=en, then assign the variable id3_default_charset=cp1251 excluding encoding problems of the user? It's still good that I manually found a solution how to display tags correctly in 1251, but I killed a lot of time watching a lot of icons in the playlists.

Translated with www.DeepL.com/Translator (free version)

**Comment by gunqqer** [comment]
Re: Equalizer #745 won't fix

**Comment by hikikomori4** [comment]
gunqqer, Thanks for your help, I updated the post using google transliteration.

> Re: Equalizer #745 won't fix

What does it mean? What they don’t want in principle, or have they postponed it for later?

**Comment by nefthy** [comment]
> gunqqer, Thanks for your help, I updated the post using google transliteration.

Please keep the discussion here in english if possible and also try to make one post per issue. 

> > Re: Equalizer #745 won't fix
> 
> What does it mean? What they don’t want in principle, or have they postponed it for later?

It means it was discussen in the metioned Issue #745 and the result of the discussion was that this will not be done, because it would require large changes to who cmus works.

**Comment by hikikomori4** [comment]
nefthy I'll do that next time, this time let me leave it as it is. 
About Issue #745  - If they don't want to write their own module, let them take [cava](https://github.com/karlstav/cava) as a dependency and show it in their frame. I do the same thing in the tmux multiplexer, but this is convenient only because I constantly use tmux and I have autosave sessions configured in it.

**Comment by hikikomori4** [comment]
@nefthy  The lack of equalizer in cmus is not the biggest problem in the ones I have described.
The developers still haven't answered here. I'm afraid that on other questions I will get the answer "do it yourself"  =(
Unfortunatelly, I simply python-junior, not cpp programmer.

**Comment by nefthy** [comment]
The only development that happens in cmus is from code contributions.

**Comment by thealio** [comment]
> Translation via deepl.com: I am using cmus because I like vim-like. There are a few requests, which I've summarized below.
> 
> THE INCOMPLETENESS OF VIEWS 2,3 In Sorted library view (2) and playlist (3) do not show the album tag. Only artist and name. It is impossible to understand which album the song is from. In Library view (1) it is displayed. This does not allow to fully use any modes except the 1st, only in addition.
> 
> THE PROGRESS BAR OF THE TRACK BEING PLAYED. It is inconvenient to read the position in the track from the numbers - 00:14 / 01:50 . For a music player, a basic part like the progress bar is very lacking. The ncurses library obviously can do something like that: [""""""""""""""55%"░░░░░░░░░░░░░░░░] What's missing is the memory of the playback position by DETERMINATION after exiting the program when listening to audiobooks.
> 
> EQUALIZER There is not enough graphic equalizer to visualize the sound. It's not just a decoration, I can see what sound is there and what level it is when I run cmus via ssh on a remote machine which I can't hear. So far I save myself by running cmus and cava in a tmux session.
> 
> SCROLLBAR. Vim style and all, but not enough vertical scrollbars in libraries. When there's a lot of music, you can't tell what % of the list roll you're in. Alphabetical sorting is indirect, but when several hundred tracks start with one letter, it doesn't work.
> 
> MUSIC TAG VIEW & EDIT Surprisingly this is not available, there is no viewer and editor for all the track(s) tags. There is no possibility to see all the track's tags, its path and file name on one screen. Given that not all the tracks are not filled correctly and appears menagerie of tags, quickly within the program to look at it and fix it is not possible.
> 
> ENTERTAINMENTS The tracks are added to the ~/.config/cmus/lib.pl database first, and then cmus works with it. Why in case of a missing track don't you suggest to search for it by existing paths? Most likely it was just renamed, why complicate life with tedious manual addition?
> 
> Also very distracting is one big dump of database for the whole program. Either I have everything in a pile, or every time I have to jump through folders and add the right artists, agonize with playlists and keeping them up to date. I'd like tab support so I have music in one place, audiobooks in another, junk in a third. And everything is available instantly, not by :clear :add path/folder. Tabs are a simple and convenient solution!
> 
> DEFAULT ENCODING. Why not check at startup the system language and if for example: LANG=en_U.UTF-8, LANGUAGE=en, then assign the variable id3_default_charset=cp1251 excluding encoding problems of the user? It's still good that I manually found a solution how to display tags correctly in 1251, but I killed a lot of time watching a lot of icons in the playlists.
> 
> Translated with [www.DeepL.com/Translator](http://www.DeepL.com/Translator) (free version)

I really need a good TAG EDITOR built in with cmus
I cannot find a good CLI/TUI tag editor

**Comment by pgaskin** [comment]
This issue is not directly actionable. Please open a separate issue for each request.

> THE INCOMPLETENESS OF VIEWS [...] Sorted library view (2) and playlist (3) do not show the album

What do you propose cutting off from the other views? There's only so much space on the screen, so something would have to go.

> THE PROGRESS BAR OF THE TRACK BEING PLAYED

Done in #1318.

> EQUALIZER

I'm not convinced this is in scope for cmus...

> SCROLLBAR

Feel free to open a PR. You'd need to add an option to reserve 1 column of space and draw a scrollbar when the window is updated.

> MUSIC TAG VIEW & EDIT

So far, cmus has treated audio files as read-only. As such, I don't think this is in scope for cmus.

> ENTERTAINMENTS [...] in case of a missing track don't you suggest to search for it by existing paths

Done (in a slightly different way) in #1085.

> DEFAULT ENCODING

Hmm... this would need a bit of thought since cmus hasn't handled encodings consistently in the past. Open another issue for this.

> TABS SUPPORT

This is almost out of scope for cmus, but if someone contributes a way to open filters as a "tab"/view without making a mess out of the view logic hardcoded in cmus right now, it might be okay.
