### ISSUE TITLE
Cmus handles ID3 Tag and MP4/AAC Tag differently when sorting by Artist

### ISSUE THREAD

**Issue by Velofil** [cmus/cmus#1164]
I noticed that all my Artists get sorted in a different way. Some are sorted by their last name and some are sorted by their first name. After some searching I noticed that all songs with ID3 Tags (*.mp3 files) are sorted correctly by their last name (for example Bakken, Rebekka under "B") and all files with MP4/AAC Tag are sorted by their first name (Rebekka Bakken unter "R"). 
Somehow Cmus seems to handle tags differently. Is that supposed to be the case? It does not make sense to me.

**Comment by gavtroy** [comment]
What's probably happening is that cmus is built without the mp4 plugin (#1112 etc.) and falling back to the ffmpeg plugin. Experimentally, in this case it seems we're returned a "sort_artist" (mp3) or "artist-sort" (mp4) rather than "artistsort" as used by id3. It should be a simple matter of adding additional entries to the substitutions `key_map` in comment.c.

Of course it could simply be that you don't have "Sort Artist" / "Sort Album Artist" tags in your mp4 files.

**Comment by Velofil** [comment]
> Of course it could simply be that you don't have "Sort Artist" / "Sort Album Artist" tags in your mp4 files.

I have checked and all files have "Sort Artist/ Sort Album Artist" tags in them (all files are tagged with Picard)
Any idea how I can fix this?

**Comment by Velofil** [comment]
Thank you for answering my support request. Does that mean the issue will be fixed in a future release? (I am new to this github thing ;-)

**Comment by gavtroy** [comment]
It still needs to be reviewed and merged into the main codebase. After that it would be included in the following release. Releases have been fairly infrequent so depending on how things line up that could either be soon (#1157) or quite a long time away.

You can try this change either by building the dev branch, or extract (twice) the PR artifact [cmus (ubuntu-20.04, gcc).zip](https://github.com/cmus/cmus/suites/5061185771/artifacts/150203270) and run it as `CMUS_LIB_DIR=./usr/local/lib/cmus ./usr/local/bin/cmus`
Then an `:update-cache -f` should hopefully get the right tags (and they should also be cached if you switch back to a version without the fix). If it doesn't work for you, that'd also be useful to know.
