### ISSUE TITLE
No mod support On MacOS

### ISSUE THREAD

**Issue by Rogerskelamen** [cmus/cmus#1170]
---

1) `uname -a`:
```
Darwin 192.168.0.101 20.6.0 Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:45 PST 2022; root:xnu-7195.141.19~2/RELEASE_ARM64_T8101 arm64
```

2) `cmus --version`:
```
cmus v2.9.1
```

3) `cmus --plugins`:
```
Input Plugins: /opt/homebrew/Cellar/cmus/2.9.1/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /opt/homebrew/Cellar/cmus/2.9.1/lib/cmus/op
  coreaudio
```

Hi, at first I have to say that I'm a new here.
I have installed `libmodplug` and `libmikmod`, but you can see here My CMus still doesn't support mod.
```
Warning: libmikmod 3.3.11.1 is already installed and up-to-date.
To reinstall 3.3.11.1, run:
  brew reinstall libmikmod
Warning: libmodplug 0.8.9.0 is already installed and up-to-date.
To reinstall 0.8.9.0, run:
  brew reinstall libmodplug
```
This is my first time to use terminal music player, I don't know what is going wrong.

**Comment by Jlw111** [comment]
Your install isn't working as expected because cmus ignores those plugins unless it is specifically built from source and told to include them.

To do this with homebrew, run `brew edit cmus` and add to the bottom of the `depends_on` block two lines: `depends_on "libmodplug"` and `depends_on "libmikmod"`. Then, where it says `system "./configure" with a bunch of `CONFIG_XXX=n` statements, add two new statements to the list, separated by commas: `"CONFIG_MIKMOD=y", "CONFIG_MODPLUG=y"`. Then, save the file.

Lastly, run `brew reinstall --build-from-source cmus`. This will build cmus with the mod plugins enabled. Homebrew will automatically keep this build up to date.

**Comment by Rogerskelamen** [comment]
You really saved my day! Thanks!
Well, I may need to learn more about how Homebrew works, but now I'm going to enjoy my mod music with my iTerm2. 🥳
Thank you again!
