### ISSUE TITLE
Gapless playback with m4a(MPEG-4)

### ISSUE THREAD

**Issue by Subtlecobra3864** [cmus/cmus#1280]
Is gapless playback supported with M4A files? As I understand, it's supported by MP3 files and FLAC files, however all of my music was ripped from iTunes and is in the M4A format.

**This is probably the wrong place for this so lmk if it should go somewhere else** :)

**Comment by gavtroy** [comment]
I tried encoding [gapless_WAVPACK_free_of_right.zip](http://tiffman.com/gtkpod/gapless_WAVPACK_free_of_right.zip) with fdkaac and none of the Linux players I tried played it gaplessly. Even the wav files the faad tool spits out have gaps. I tried again with neroAacEnc and didn't fare any better. I don't know if I'm doing something wrong or the whole system is just broken.

**Comment by Subtlecobra3864** [comment]
That's annoying. Could it be that m4a is an encoded format? I'm pretty sure all of my music has Apple's weird iTunes encoding too so that could be another issue as I've heard that it doesn't follow the standard spec for m4a files.

**Comment by gavtroy** [comment]
I eventually looked into it more and have raised a PR that should work for both the (older?) iTunSMPB tag and the more standardized but very convoluted Edit List approach described in https://developer.apple.com/documentation/quicktime-file-format/appendix_g_audio_priming_handling_encoder_delay_in_aac . For the few files I tried this seemed to work well so hopefully I've covered the various cases adequately. More testing would definitely be welcome.

`faad` turned out to be an unfortunate reference as, while it claims to support gapless decoding, it doesn't implement either solution for determining Encoder Delay (silence at the start) and even the code it has for removing the Remainder samples was broken when I tried it. Maybe I just didn't look hard enough but the only player I tried that was gapless was Strawberry. Audacious, DeaDBeeF, musikcube, mpd, and even mpv seem not to be.
