### ISSUE TITLE
.m4a issues in latest Ubuntu

### ISSUE THREAD

**Issue by flyingmutant** [cmus/cmus#211]
https://bugs.launchpad.net/ubuntu/+source/cmus/+bug/1311337
https://bugs.launchpad.net/ubuntu/+source/cmus/+bug/1389212

**Comment by thehodapp** [comment]
Is there a temporary fix?

**Comment by flyingmutant** [comment]
Can you try to compile cmus with plugins by hand using latest git version, and see if the issues are still present?

**Comment by IonicaBizau** [comment]
My brother, @GhitaB, also had same problem with `wma` files.

**Comment by sleepymurph** [comment]
Hi. I'm running Debian Jessie (8.5) and I had the same problem with M4A files when running the distribution's version of Cmus (based on 2.5.0, with AAC plugin enabled -- `cmus_2.5.0-7+b1_amd64.deb`). It would attempt to add the files and then segfault.

I did install by hand from git and there was no problem. It adds and plays the problem M4A files just fine. This is both with the latest version (v2.7.0-144-g37f4daa -- 37f4daaea4d2724cd2b4d66984cf72b012ef5d48) and checking out the v2.5.0 tag. I used a very minimal build config though (basically just MOD and AAC enabled).

I used a minimal configuration since I didn't have any of the development packages for the libraries installed. I had to figure out which they were and install them one-by one. I might investigate more if I have time, but I don't do much C development nor digging into packaging, so I'm in unfamiliar territory and I might be missing some clues that others might find obvious.

Some details:

- Debian version: Jessie / 8.5
- Problem Debian package version: `cmus`, version `2.5.0-7+b1`
- Successfully built from Git with versions:
    - master: `v2.7.0-144-g37f4daa` (37f4daaea4d2724cd2b4d66984cf72b012ef5d48)
    - tag: `v2.5.0` (6bfa436d3b2dc01d7e29863fc1be54af88c9faeb)
- Successful build `configure` options: `CONFIG_MAD=y CONFIG_AAC=y CONFIG_PULSE=y CONFIG_ALSA=y CONFIG_ROAR=n`
- `libmp4v2`/`libmp4v2-dev` version: `2.0.0~dfsg0-3`
- `libfaad2`/`libfaad-dev` version: `2.7-8`

**Comment by sleepymurph** [comment]
Update: I rebuilt the Debian cmus 2.5.0 package on my system and installed it (following [this guide]( https://wiki.debian.org/BuildingTutorial)), and M4A files work fine. I can't reproduce the bug. So I'm out of ideas for now. Something in the maintainer's configuration?

**Comment by mahkoh** [comment]
I don't see a path forward here. According to the linked pages this is a 2.5-only bug that has long since been fixed. Downstream is unwilling to ship newer versions or backport the fixes. There is nothing to be done on our end.
