### ISSUE TITLE
play a song several times on random mode

### ISSUE THREAD

**Issue by ghost** [cmus/cmus#226]
Hi, i will love an option to listen your favourite song after play X songs on random shuffle mode. So even our songs order is random, we can still listen our favorite song/songs after listen X random songs.
Thanks! I hope see this easy but powerful feature son :)

**Comment by pgaskin** [comment]
IMO, this feature is a little too niche.

Also, it's not clear what you mean by "favourite song". I'm going to assume you mean the queue (though you might also mean a specific playlist).

If this were to be implemented, I can think of two ways:

- Have a counter of the number of songs to play on shuffle before playing the queue, and a command to set this counter.
- Have a command to add X placeholder tracks to the queue, which cause cmus to skip the queue logic if it consumes it.

Nevertheless, since OP has vanished, the feature is very specific, and there isn't any upvotes or comments from anyone else, I'll close this for now.
