### ISSUE TITLE
Library is often empty after start

### ISSUE THREAD

**Issue by fin0** [cmus/cmus#241]
Hi there,
I didn't really figure out when exactly this is happening, yet: My problem is that the library is often empty after the start. I THINK it happens when I shut down the system while cmus is still running (I use it in tilda, so it is easy to forget to quit it) but I'm not exactly sure if this is the reason.

Is this a known problem? I really don't want to add my library by hand after every start.. Thanks in advance for helping :)

**Comment by flyingmutant** [comment]
This almost certainly happens because you force-quit cmus during your system shutdown. Just use `:quit` command at least once to exit cmus — preferably every time, of course — or make sure that tilda is sending SIGTERM to cmus on shutdown, *and* that there is enough time for cmus to write its cache and for it to be flushed to disk properly.

**Comment by fin0** [comment]
Ok I understand why this can happen, BUT:
I couldn't imagine happening this in a player with gui and I think you consent with this. For a music player (gui or not) it is just common to keep it running all the time in the background and eventuelly shut down your system without quiting it. Is there any technical problem to change cmus to behave like any music player?
So the problem is that cmus gets a shutdown-signal and starts flushing the cache but can't finish it? If this is true, maybe one can just add a preference that flushing cache before quiting should not be done?
Thank you!
