### ISSUE TITLE
Too Many Arguments?

### ISSUE THREAD

**Issue by Vagour** [cmus/cmus#349]
Whenever I try to do anything I get this error saying too many arguments. I tried looking into like doing a clean install of the app but I couldn't figure out how to completely remove the one I have installed now.

**Comment by flyingmutant** [comment]
Please specify *exactly* what commands you are trying to execute, what is the output you get from them, and what output you expect.

**Comment by Vagour** [comment]
It happens when I try to do anything, the command I’m using is *5* to open File Browser and when I use my arrow keys to try to move down the list I get that error. There was a point when it was working fine and I hit some keys by mistake and it like screwed everything up. Is there a way I can just remove this and do a clean install?

**Comment by flyingmutant** [comment]
Remove the files `~/.cmus/rc` and `~/.cmus/autosave` (or `~/.config/cmus/rc` and `~/.config/cmus/autosave`).

**Comment by Vagour** [comment]
Can you inform me on how to search and find that file? I'm sorry about this completely new to this :(

J. Love

**Comment by jayay** [comment]
`~` is your home directory.
If you open a terminal and type `ls ~/.cmus/` and `ls ~/.config/cmus` you'll see which one of them is being used, because the command says "No such file or directory", if the file or directory you want to list (that's what ls does), doesn't exist.

You can then delete the two files @flyingmutant listed above by putting `rm ` in front of them.

If you want to use a graphical file manager to delete the two files, make sure your file manager displays hidden files (hidden files begin with a dot, on Gnome you can activate that by pressing `ctrl + h`).

**Comment by Vagour** [comment]
So I typed it as rm ls ~/.config/cmus and rmls ~/.config/cmus and it says no such file or directory

then it says rm: /Users/JayyLove/.config/cmus: is a directory but when I type 

rm /Users/JayyLove/.config/cmus: its says no such file or directory lol

**Comment by jayay** [comment]
`rm ~/.config/cmus/rc` and `rm ~/.config/cmus/autosave` should work.
