### ISSUE TITLE
cmus-remote --pause toggles playback, not pause it.

### ISSUE THREAD

**Issue by kingy9000** [cmus/cmus#403]
I am trying to use `cmus-remote -u` to only pause playback when I lock my screen, but it can only toggle playback status. The problem with using `cmus-remote -s` is that it starts the current song from the beginning when I play it again, which is annoying for a long mix of songs.

I have made a work around for this by checking `cmus-remote -Q` to check if cmus is even playing before running `cmus-remote -u` but this sounds like a feature that should be implemented into cmus itself since that would be more efficient and neater.

I understand that `cmus-remote -u` needs to toggle playback instead of only pausing to be able to use cmus with media keys, but this could be worked around by adding an extra option that only pauses cmus.

Thanks for reading.

**Comment by jessebolson** [comment]
+1

**Comment by jolange** [comment]
I also think there should be separate commands for `pause` and `pause/play toggle`. I could try to implement this, but I'm not sure if one should break the current `pause` behaviour and add a further `toggle` option, or keep the current `pause` behaviour and add a `pause-only` option.

Since this would be a change in cmus itself and not only for `cmus-remote`, I think breaking the current behaviour would be annoying to most users. @flyingmutant what do you think?

**Comment by flyingmutant** [comment]
As for compatibility with status quo – we should definitely preserve current behavior. PR adding new commands would be very welcome.
