### ISSUE TITLE
CoreAudio plugin sample rate syncing issue

### ISSUE THREAD

**Issue by flovouin** [cmus/cmus#432]
Hi guys,

Thanks to the CoreAudio plugin #374 , I no longer have warning messages about using deprecated APIs when using cmus on OSX.

However I have a small issue when using bluetooth headphones: it sounds like every other frame is skipped. Also, it changes the codec from apt-X to SCO, which results in terrible quality in other apps that play audio. The problem does not occur when I don't use cmus. Once the codec has been changed to SCO by cmus, it can only be reverted by turning the headphones off and on.

The problem can be solved by setting
`set dsp.coreaudio.sync_sample_rate=false`
However, I wonder if this should really happen?

By looking at what happens in `coreaudio_sync_device_sample_rate`, I can see that my headphones can handle sample rates of 8 or 44.1kHz. [Setting the sample rate](https://github.com/cmus/cmus/blob/master/coreaudio.c#L462) does not seem to be an issue, however [setting the format](https://github.com/cmus/cmus/blob/master/coreaudio.c#L498) messes up the codec (changes it to SCO). Setting the format does not fail, it simply doesn't look to be the right one.

I'm happy to provide more data if needed.

Cheers,

1) `uname -a`:
```
Darwin (OSX El Capitan 10.11.4, on both an iMac and a MacBook).
```

2) `cmus --version`:
```
7b5297a
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/HEAD/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/Cellar/cmus/HEAD/lib/cmus/op
  coreaudio
  ao
```

**Comment by flyingmutant** [comment]
@Wang-Yue any ideas?

**Comment by Wang-Yue** [comment]
Thanks for the bug report and investigation. 

First, some background for sync_sample_rate. 

I added this functionality since audiophiles want bit-perfect output. Many audiophile players such as VOX, foobar2000,  and Audirvana, have it too. A user may have contents of different formats in their music library, and an automatic switch option can let user always have bit-perfect output when changing songs. It may make those audiophile users feel better --- I personally don't really care about this feature, since all my audio files are in CD format, and the speaker I use to play those CDs only supports 44.1KHz 16bit integer as input. 

I combined both functionalities (setting sample rate *and* physical format [the wave data type, such as 16bit signed integer]) into one setting, since bit-perfect output requires both to be satisfied. The setting should be called sync_sample_rate_and_physical_format or enable_bit_perfect_playback to be technically correct. 


-- tl;dr start. skip the next three paragraphs

sync_sample_rate is an pro user setting, because kAudioStreamPropertyPhysicalFormat depends on whether the hardware (or hardware driver) correctly implements it. It also doesn't reflect what user actually want, or the optimal option available.

An application should never be supposed to change the user device preference (sample rate and physical format) without user's consent, since it may mess up what other application is doing with the device. That's why it's a pro feature that's by default off, and I only recommend using it when user "hog" the device (so that no other app can interfere with it). There's an option to hog the core audio device in cmus. 

I have a few output devices that work perfectly, but I also have one piece of device that does not quite work. That device, when set the physical format, AudioObjectSetPropertyData  will always return a success (noErr OSStatus), but the actual physical format remains unchanged.  It can play audio fine, but just not bit perfect. 

-- tl;dr end

Then, let's look at the problem you described.

My guess is the audio file you are playing happens to be a format that is only supported by SCO codec. When you are using a normal media player (such as iTunes), or if you turn the feature off, CoreAudio will automatically convert your audio format to a format that's supported by aptX. Internally, CoreAudio will convert all audio stream to 32bit float, and then mix it, and then convert it to a format that's supported by your bluetooth audio codec. but having sync_sample_rate=true will force it to convert to a format that's the same as your source audio file, which may not be supported by your bluetooth audio codec at all. So if I'm right, and if you insist that you want it to give bit-perfect output, there's nothing else it can do.

You may only want to avoid CoreAudio SRC (sample rate conversion), since SRC are usually lossy. In this case, you probably want to split the setting into two --- one for sample rate only, and the other for physical format. Does it sounds more reasonable?

**Comment by flovouin** [comment]
Hi Wang-Yue,

Thank you very much for your detailed explanation, it makes things much clearer. From looking at the code I had guessed that the `sync_sample_rate option` was setting the format for the samples, but I hadn't realised the implications for the device.

To be honest I wasn't actively trying to set the sample rate / physical format for the device. It turns out that `sync_sample_rate` was set to `true` by default when I launched cmus, and this is actually how I discovered the option. So I guess I've got a much simpler solution: could you make sure the option is turned off by default? I see that `coreaudio_opt_sync_rate` is set to `true` in `coreaudio.c`, is this where the parameter gets its default value?

Now that I've understood what the option does, it is unlikely I will need it, especially for bluetooth headphones. Simply setting the option to `false` in my cmus `rc` does the trick as far as I'm concerned. Maybe other people would be interested in having two separate settings (sample rate and physical format), but dont feel the need to implement that just for me ;-)

The only question left is, why doesn't CoreAudio return an error when setting the physical format to a configuration that the hardware won't be able to handle? But that's probably not for you to answer!

Cheers,

**Comment by Wang-Yue** [comment]
My bad. that option should default to false. I'll send a PR to solve it asap.

**Comment by flyingmutant** [comment]
https://github.com/cmus/cmus/pull/435 is now merged.

**Comment by flovouin** [comment]
Awesome, thanks for taking the time to answer my questions and change this!
