### ISSUE TITLE
Support for the audio framework used on Android (OpenSL ES)

### ISSUE THREAD

**Issue by Neo-Oli** [cmus/cmus#437]
It would be great if cmus would support the Android audio framework, so it can be made to run on [Termux](http://termux.com). 
Here is the Termux Package request: https://github.com/termux/termux-packages/issues/209

**Comment by Neo-Oli** [comment]
https://www.bountysource.com/issues/33102790-support-for-the-audio-framework-used-on-android-opensl-es

**Comment by ackalker** [comment]
tinyalsa isn't guaranteed to be on every Android device, OpenSL ES is (sadly, perhaps, but true). Personally I'm thinking of repurposing tinyalsa to have it talk to OpenSL ES instead of to the kernel. Because it is much smaller than libalsa, I think this is doable. If there aren't too many Linux applications which require patches or stubs for functionality which tinyalsa doesn't expose, this could work out nicely.

**Comment by ackalker** [comment]
Work on ALSA (and Pulseaudio) in Termux is progressing. See termux/termux-packages#821

**Comment by pgaskin** [comment]
Termux currently has working pulseaudio support, and I'm not aware of any platform cmus is used on which doesn't support the existing output plugins.

@nefthy, this issue should probably be closed.

**Comment by nefthy** [comment]
I don't think an android port is probable.

**Comment by pgaskin** [comment]
As of #1346, cmus now natively supports audio on Android 8.1+. Compared to pulseaudio, this has no external dependencies, lower latency, proper multichannel support, better battery life, and `pause_on_output_change` support.
