### ISSUE TITLE
FLAC plugin does not work for small files

### ISSUE THREAD

**Issue by Noah0504** [cmus/cmus#440]
Using version 2.7 from GitHub, but this also happened on version 2.5 from Debian stable repository.

I have two tracks from the same album that are being sorted under <No Name> in Cmus.  The album was ripped by me and the tags were edited by me with the same program, so they are identical.

The only think I can think of that is different, is the tracks are less than 10 seconds long.  1 is 10 seconds long and the other is 9.  Is Cmus having an issue with tracks this small?  BTW, they are FLAC files.

**Comment by mahkoh** [comment]
Can you provide the files?

**Comment by Noah0504** [comment]
Here they are.

[Songs.tar.gz](https://github.com/cmus/cmus/files/252772/Songs.tar.gz)

**Comment by mahkoh** [comment]
This is a bug in the libflac plugin or libflac. Delete the libflac plugin.

```
sudo rm /usr/local/cmus/ip/flac.so
```

**Comment by mahkoh** [comment]
Assuming that you've ffmpeg installed.

**Comment by Noah0504** [comment]
Well, now I can't play or add FLAC files.  I have ffmpeg installed, but maybe I'm missing something else.  I'll check this in a bit.

**Comment by mahkoh** [comment]
You need the ffmpeg plugin. Check

```
cmus --plugins
```

**Comment by mahkoh** [comment]
@flyingmutant Is there any argument against changing the ffmpeg priority to be higher than the priorities of all other input plugins?

**Comment by Noah0504** [comment]
I'm back to using version 2.5 as it has the ffmpeg plugin, but things still aren't working.  Cmus just crashes anytime I try to do anything with the files.  If I try to add them, I get a "segmentation fault".

I'll try building latest release with ffmpeg support when I get a chance.

**Comment by Noah0504** [comment]
BTW, thanks for all of the help.

**Comment by Noah0504** [comment]
Ugh.  I cannot seem to get ffmpeg.c to build.  I'm giving up for now.  I can just live with the issue.  BTW, do you know what exactly the bug in flac plugin is?

**Comment by mahkoh** [comment]
No. But the flac plugin can't even play the files.

**Comment by flyingmutant** [comment]
@mahkoh yes, there is a strong argument against increasing ffmpeg plugin priority. It is one of the least tested plugins, and it breaks all the time, because ffmpeg developers can not maintain a stable API.

Slightly better idea would be to add new options for controlling output plugin priority (for occasional workarounds like this one). But the best thing is to find a bug in flac plugin and fix it, of course.

**Comment by mahkoh** [comment]
>It is one of the least tested plugins

Maybe so, but the plugins are not very large. More important is how much the input libraries are tested. And in this area I claim that ffmpeg beats all other libraries by a large margin. It's used in many multimedia applications such as firefox, mpv, mplayer, audacity, youtube-dl, etc. It also gains support for new formats quickly and is evidently actively developed.

On the other hand, libmad is apparently dead and libflac hasn't seen a release in over a year. Which would not be bad if those libraries didn't have bugs and other issues.

>it breaks all the time, because ffmpeg developers can not maintain a stable API.

I don't think this is relevant. The IP priority is a user-facing issue while maintaining the plugin is a developer-facing issue. The user does not care if the plugin has to be updated twice a year as long as it delivers a better user experience.

>But the best thing is to find a bug in flac plugin

If the bug is in the plugin and not in libflac itself.

**Comment by Noah0504** [comment]
> If the bug is in the plugin and not in libflac itself.

I will say that Rhythmbox appears to handle them correctly, so perhaps it is not libflac.

**Comment by intact** [comment]
Functions flac_open and flac_read are broken for too small (less then 8kB) files.

Maybe you can try something like this https://github.com/intact/cmus/commit/7e1a7c03a95997a0910cbb729239d7777f5ac481

**Comment by flyingmutant** [comment]
@mahkoh it is totally unknown if ffmpeg will provide any better experience to cmus' users. MAD and FLAC plugins (and libraries) are extremely well tested, and vast majority of people have never experienced any problems with them.

It is not like MP3 of FLAC files are changing all the time, and people need new versions of decoding libraries to read them every couple of months. Once they work, they do not stop to work. Unlike ffmpeg: it will randomly stop to compile «just because», and it is hard to believe that constant internal changes are not causing user-facing regressions as well.

Changing the defaults is not a thing that can be done lightly; you absolutely have to be sure that you will a) not break anything that currently works, and b) improve status quo sufficiently to warrant the change.

**Comment by Noah0504** [comment]
@intact I tried building with your changes and it did not fix the issue.

I know this all seems a little trivial for two songs of essentially silence, but this isn't the only album ever to have included tracks like this, and I think it's important to be able to keep the structure of an album.

So, having said that, thanks for acknowledging the issue and taking the time to try and fix it.

**Comment by intact** [comment]
@Noah0504 try to delete cache file first

**Comment by Noah0504** [comment]
@intact You're right, that did the trick.  Working perfectly.

**Comment by flyingmutant** [comment]
@intact, if you do have a proper solution, can you please submit it as a pull request, with an explanation of what exactly is fixed, and how?
