### ISSUE TITLE
Separation of plugin-specific code

### ISSUE THREAD

**Issue by vit1-irk** [cmus/cmus#453]
Certain parts of plugins' code are stored in the player itself (especially cue and cd), so I have started to write a layer to provide these functions apart from main code.

Code (this commit separates just cue support for start) compiles successfully and doesn't make trouble, but I'm not yet sure to open pull request.

https://github.com/cmus/cmus/compare/master...vit1-irk:special_handlers?expand=1

Please watch the code and leave a comment (_да и на русском тоже можно_) if I'm doing right and which details are required to know about plugin system and these functions (to handle file names, playlist entries and special links).

Thanks in advance!

**Comment by flyingmutant** [comment]
Hi @vit1-irk,

First of all, sorry for super-delayed response — it is really hard for me to find any free time as of late :-(

The thing you do certainly makes sense, and the code looks OK in general (I have some comments, but better to leave them for the PR).

I'll close this issue — please feel free to open a PR once you will be ready. Can't promise timely review on that, unfortunately.

P.S. Let's keep the discussion in English, because this way it would be accessible to the vast majority of users/contributors.
