### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by throwaway03124** [cmus/cmus#506]
It has been over a year since the last one. When are we going to see a new one ?

**Comment by flyingmutant** [comment]
Yeah, it is about time: there are lots of new features. Just have to wait for everything that is in to stabilise a bit (e.g. https://github.com/cmus/cmus/issues/505).

**Comment by Wang-Yue** [comment]
any recent plans to triage bugs and make the release?

**Comment by mahkoh** [comment]
Afaik the only bug blocking a release candidate is #505. Unfortunately we've not been able to track it down yet and since I cannot reproduce it there is not much I can do to debug it.

**Comment by flyingmutant** [comment]
@Wang-Yue, you have a mac, right? Can you please try to reproduce #505?

**Comment by Wang-Yue** [comment]
@flyingmutant  I can reproduce it sometimes. When deleting all caches and playlists, and add the entire music library folder, the UI will always be corrupted. I don't have problem at each start up though.

**Comment by Wang-Yue** [comment]
@flyingmutant  I could reproduce this before when I add my entire music folder. Now I can't reproduce this any more.

**Comment by mahkoh** [comment]
@Wang-Yue If I understand you correctly you are saying that this bug already existed back in 2015?

**Comment by Wang-Yue** [comment]
@mahkoh Yes I encountered similar problem as @flyingmutant  do back in 2015, when I became a cmus user. What I did was simply importing my large music collection into cmus.  The UI corrupted while loading all the tracks. a simple CTRL+L would fix the problem. This could be reproduced reliably on my machine. 

However I can't reproduce this now with the latest bits.

**Comment by Wang-Yue** [comment]
I have an old cmus installation that could reproduce the problem. 

<img width="1440" alt="screen shot 2016-10-29 at 10 42 56 am" src="https://cloud.githubusercontent.com/assets/889340/19831673/d1531f58-9dc4-11e6-89a5-57eae0d939aa.png">

This happens with 9d37708a93c9fadeebe0eb9f8f67310e4fe55156. 

```
$ cmus --version
cmus v2.7.0-110-g9d37708
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

**Comment by Wang-Yue** [comment]
I pull the latest commit and the problem disappear.

**Comment by mahkoh** [comment]
@flyingmutant What do you make of this? I think the situation is that this bug has existed for over a year. It might even be in 2.7. But nobody ever reported it. The thing that changed now is that it's happening to you. But we do not know if the frequency with which it happens has increased since the 2.7 release. Should we just put out an RC and collect some feedback?

**Comment by flyingmutant** [comment]
Yeah, it might be an old bug lurking around.

I am OK with making an RC now -- since I am not making any progress on #505 myself, and just waiting is not very productive. Maybe put in the release notes mention a request to looks for UI corruptions, to know how widespread this is.

Do you consider everything RC-ready?

P.S. These races (like #505) and deadlocks (like #574) look to me like a sign that internals are in a bit of a mess. It'd be nice to make data and control flows simple and explicit, to transition from "no obvious defects" to "obviously no defects" (not for this release; maybe for 3.0).

**Comment by mahkoh** [comment]
>Do you consider everything RC-ready?

Sure.

>P.S. These races (like #505) and deadlocks (like #574) look to me like a sign that internals are in a bit of a mess. It'd be nice to make data and control flows simple and explicit, to transition from "no obvious defects" to "obviously no defects" (not for this release; maybe for 3.0).

This deadlock issue was unfortunately introduced recently when I removed the explicit locks. The fundamental problem is that we're using three different ways to communicate between threads:

1. Mutexes

2. Synchronous message passing (cmus_get_next_track)

3. Asynchronous message passing (job results)

Synchronous message passing alone is already dangerous because if two threads try to do it at the same time with each other you get a deadlock even though no locking is visible in the code. Ideally I'd like to move everything over to async message passing but that probably requires a rewrite of player.c.

**Comment by nefthy** [comment]
> but that probably requires a rewrite of player.c.

I think that is a good idea, for the next release or so.

**Comment by flyingmutant** [comment]
https://github.com/cmus/cmus/releases/tag/v2.8.0-rc0 (finally!)

I hope I've got release notes right, and have included everything important there. Now, it's time to update the website, and also prepare v2.7.2.
