### ISSUE TITLE
Modernize cmus code

### ISSUE THREAD

**Issue by Wang-Yue** [cmus/cmus#530]
Discussed with @mahkoh at https://github.com/cmus/cmus/pull/528 

During the dev process I found it hard to 

- maintain deprecated APIs (ffmpeg, flac)
- follow C89. many important C99/C11 features are missing

We need at least move the codebase to C99/C11. Moving to C++11 and up will benefit more I believe:

- everything is object --- plugins will be cleaner and have good design pattern
- container classes can be used to replace various data structures in use
- reduce the messy string handling

take a look at tree.c --- it's entirely not maintainable this way without C++

Build system is pretty old too. I'd like to see it's migrating to cmake or similar systems.

**Comment by mahkoh** [comment]
>maintain deprecated APIs (ffmpeg

I think everything older than 1.0 should be dropped. The two distributions that concern me Ubuntu 14.04 and Debian Wheezy. Ubuntu 14.04 should have 1.0 in its repos (but just so.) Someone should test this. Wheezy has more recent versions in backports.

>follow C89. many important C99/C11 features are missing

cmus already uses C99. C11 after #511 

>Moving to C++11 and up will benefit more I believe:

I don't think so. The only thing I'm missing from C++ is generic containers. Everything else can be done just as well in C without the added complexity of C++.

>take a look at tree.c --- it's entirely not maintainable

What do you mean by this?

>Build system is pretty old too. I'd like to see it's migrating to cmake or similar systems.

I've recently the build system in cmake (alas some plugins are missing) https://gist.github.com/anonymous/3c5ccf0778c7af519fa167c3d4997a2e

But I decided that it wasn't worth the trouble. The current system works fine and in some ways better than what cmake can do.

**Comment by Wang-Yue** [comment]
> cmus already uses C99. C11 after #511

compiler flag is no eq to use. Code must be updated, too. start from those forward declaration. 

> I don't think so. The only thing I'm missing from C++ is generic containers. Everything else can be done just as well in C without the added complexity of C++.

Apart from generic containers there are a lot of things in C++. Prettier RAII resource management. Faster speed. Clearer object dependency. 

C++ code can be very simple and readable if done right. For instance Apple's IOKit, Google's protobuf. We just need to restrict ourselves to a very subset of C++. 

For instance C++ will give the following benefit:
- inherit input/output plugin from interface. This is huge step to make things cleaner.
- static varibles in each file will now be private member. 
- replace char* to std::string.
- RAII mutex/locks in player.c
- replace rb tree, lists, etc with containers
- create a abstract interface for UI (so one can create alternative to ncurses. Qt/Cocoa UI).
- many goodies (such as ring buffer implementation in coreaudio.c) can be shared to other classes (such as player.c)

**Comment by nefthy** [comment]
I don't see any good reason for changing the language. I also don't see any reason for implementing interfaces in Qt or other toolkits. There are other players that do that already.

cmus is a music player with a vim-style curses interface written in C. If you want a Qt/Cocoa player written in C++, well cmus is none of that.

**Comment by Wang-Yue** [comment]
> I don't see any good reason for changing the language. 

That's your opinion. I don't care. 

>I also don't see any reason for implementing interfaces in Qt or other toolkits. There are other players that do that already.

None of them reaches the level how cmus handle audio.

> cmus is a music player with a vim-style curses interface written in C. If you want a Qt/Cocoa player written in C++, well cmus is none of that.

It's about using the right pattern rather than functionality itself.

**Comment by flyingmutant** [comment]
> cmus is a music player with a vim-style curses interface written in C. If you want a Qt/Cocoa player written in C++, well cmus is none of that.

Amen.

cmus will stay what it is. More modern C is welcome, cleaner code is welcome, but C++ is not. 

Believe me, there are lots of good reasons to stay with C. I've spent 5 years writing (modern) C++ on my past job. I've read all the popular books, I follow Boost releases, I have a copy of standard downloaded for reference — so I know a bit what I am talking about.

Modern C++ is cool, Rust is cool, Go is cool. But cmus is, and will be, a C project.

Lets try to avoid the language discussion, as it will not be productive.

**Comment by nefthy** [comment]
>> I don't see any good reason for changing the language.
> That's your opinion. 

Well thats the reason I started that sentence with "I don't see"

> I don't care.

Well there is a fork button on top, feel free pressing it and doing whatever you care about.

**Comment by flyingmutant** [comment]
Hey, hey, guys, please calm down!

Let's keep this friendly 🍻

**Comment by nefthy** [comment]
Sorry, my reaction was a bit unprofessional, however "That's your opinion. I don't care." is not a statment fitting very well in a collaborative project.

**Comment by mahkoh** [comment]
>* inherit input/output plugin from interface.

How is that different from what we're currently doing with function pointers?

>* static varibles in each file will now be private member.

I don't see how a singleton is better than global variables.

>* replace char* to std::string.

String handling in C++ is severely lacking compared to some other languages. I don't see how it would be an improvement.

>* RAII mutex/locks in player.c

That would be nice but most of the problems in that area can be solved by writing smaller functions with a single entry and exit to avoid excessive gotos. C also supports RAII via language extensions.

>* replace rb tree, lists, etc with containers

How would that improve the implementation?

>* create a abstract interface for UI (so one can create alternative to ncurses. Qt/Cocoa UI).
>* many goodies (such as ring buffer implementation in coreaudio.c) can be shared to other classes (such as player.c)

That can be done in C.


As I see it the only problem here is that cmus has organically grown for a long time. Naturally the code looks bad in many places. I've recently been playing with a complete rewrite using various GCC extensions and some POSIX 2008 functions (ergo no OSX support.) Have a look at it here: https://github.com/mahkoh/oka. Maybe the code there is more to your liking. Since you've talking about "goodies" you might be especially interested in the "utils" directory which contains a completely freestanding library that implements many abstractions that are used throughout the program. Some of that can surely be included in cmus.

**Comment by flyingmutant** [comment]
So, I'd say there is a consensus on gradually removing support for super-outdated libraries and modernizing the C code style. I am not a fan of language extensions though — I'd prefer to keep it simple.

Closing, since this issue has no definition of «done/fixed» — but feel free to continue discussion here.
