### ISSUE TITLE
Segmentation fault after 21 seconds playing mp4 files. 

### ISSUE THREAD

**Issue by tecfu** [cmus/cmus#662]
mp4 files play for 21 seconds, then crash with the message:  Segmentation fault (core dumped)

---

1) `uname -a`:
```
Linux hostname 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```

2) `cmus --version`:
```
cmus v2.7.1
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: ac3 aif aifc aiff ape au mka shn tta wma aac fla flac m4a m4b mp+ mp2 mp3 mp4 mpc mpp ogg wav wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  jack
  ao

```

**Comment by tagniam** [comment]
What specific mp4 file(s) cause the crash?

**Comment by whotwagner** [comment]
Do you import media-files in your library before you play those mp4 files? I experienced a similar problem: first i imported a directory full of music and after that I started to play music and after some seconds cmus crashed. I investigated the bug and figured out that it wasn't the media-file I played but the import of the media-files. I was able to locate the problem in the libcue, since it does not handle unicode encoded cue-files properly: https://tech.feedyourhead.at/content/how-i-fixed-a-bug-in-my-favourite-media-player

**Comment by pgaskin** [comment]
I'm going to close this since there hasn't been a response for 4 years. @tecfu, if you still have this issue, can you test it on the latest version of cmus with debugging enabled and post the core dump, cmus binary, and debug log so I can attempt to determine the issue?
