### ISSUE TITLE
DSD support

### ISSUE THREAD

**Issue by Madman600** [cmus/cmus#796]
Is there any way to get cmus to play DSD files?

**Comment by criztovyl** [comment]
In theory the `ffmpeg` should be able to play DSD files, could you try that via `ffprobe`, just to be sure?

I for example used [this sample file](http://samplephotovideo.com/2015/12/sample-dsd-audio-file/) and `ffprobe your_dsd_file.dsf`, produced the following output:

```
$ ffprobe ~/Downloads/01\ -\ David\ Elias\ -\ The\ Window\ -\ Vision\ of\ Her\ \(DSD64\).dsf
ffprobe version 3.3.7 Copyright (c) 2007-2018 the FFmpeg developers
... snip ...
[dsf @ 0x5655579b21e0] Estimating duration from bitrate, this may be inaccurate
Input #0, dsf, from '/home/christoph/Downloads/01 - David Elias - The Window - Vision of Her (DSD64).dsf':
  Metadata:
    title           : Vision of Her
    artist          : David Elias
    genre           : Folk
    encoder         : KORG AudioGate ver.1.5.0
    date            : 2007-11-20 22:52
  Duration: 00:05:07.11, bitrate: 5644 kb/s
    Stream #0:0: Audio: dsd_lsbf_planar, 352800 Hz, stereo, fltp, 5644 kb/s

```

If it works and you compiled cmus yourself, you could add `dsf` to the `ffmpeg.c` input plugin's extensions (e.g. after `"wav"`, or better after `"flac"`) and then recompile cmus.
https://github.com/cmus/cmus/blob/b595b8cd7fee10824e5351faf2def28ed5778e59/ip/ffmpeg.c#L477-L480

Otherwise this will turn into a "feature"-request.
Maybe there even is another way link an additional extension to an input plugin without changing the source code.

**Comment by Madman600** [comment]
I modified the source code to do that which didn't work it sounded like it was playing super slow. Then I modified ffmpeg.c around line 238 https://github.com/cmus/cmus/blob/master/ip/ffmpeg.c#L238 to default to 32 bit output but that just resulted in static.

**Comment by Madman600** [comment]
Looks like you would have to use [FLTP sample format](https://www.ffmpeg.org/doxygen/2.8/group__lavu__sampfmts.html#ggaf9a51ca15301871723577c730b5865c5a2d21c520e4ab21100b6440ec2d81ba1b) but I'm not sure how that maps to sample format bits.

**Comment by criztovyl** [comment]
I am not sure either, maybe someone else can help.

**Comment by Z3ROGRAV1TYx** [comment]
+1 for this

**Comment by antonellocaroli** [comment]
+1

**Comment by antonellocaroli** [comment]
no news for native dsd support?
maybe this will help:

https://github.com/marcoc1712/squeezelite-R2/blob/Release/dsd.c

https://github.com/marcoc1712/squeezelite-R2/blob/Release/dop.c

https://github.com/marcoc1712/squeezelite-R2/tree/Release/dsd2pcm

**Comment by hajosattila** [comment]
+1

**Comment by aljustiet** [comment]
+1

**Comment by pryid** [comment]
+1

**Comment by gavtroy** [comment]
The ffmpeg plugin has slow playback because of the effective sample rate being unsupported. Actually 353kHz "DSD 64" files work fine repeating that ffmpeg experiment today, since the latest release of cmus added support for sample rates up to 384kHz. Unfortunately "DSD 128" files (effectively 706kHz) would still be broken as well as any higher variants (although >128 seems to be uncommon anyway).

By the way I don't know anything about the "[FLTP sample format](https://www.ffmpeg.org/doxygen/2.8/group__lavu__sampfmts.html#ggaf9a51ca15301871723577c730b5865c5a2d21c520e4ab21100b6440ec2d81ba1b)" mentioned previously but I guess ffmpeg handles it under the hood because it doesn't seem to be an issue.
