### ISSUE TITLE
Error opening file unsupported format

### ISSUE THREAD

**Issue by ibrokemypie** [cmus/cmus#801]
---

1) `uname -a`:
```
Linux badhp 4.17.0-rc5-mainline #1 SMP PREEMPT Tue May 15 15:56:24 AEST 2018 x86_64 GNU/Linux

```

2) `cmus --version`:
```
cmus v2.8.0-rc0-88-gb595b8c

```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao

```
I have a number of ogg opus file that i converted with ffmpeg and play fine in other players such as mpv, however in cmus they all say ``Error: opening file : unsupported file format    ``

**Comment by KharmaScribbles** [comment]
I've had this problem in other players before, I just want to give my 2 cents on what worked in my case (mind you, this worked in the other players).

Check to see if meta tags have the files tagged as .ogg

I actually named my "broken" files "song title .ogg" so technically if file extensions were not hidden my files looked like: title.ogg.ogg

Otherwise, how did you install/build cmus? I've done some quick browsing around the web
and unless it was compiled without the proper support, there is either a bug affecting you or it's a simple file data error which would be quite easy to fix :)

I know - I'm not too helpful. Sorry.

**Comment by ibrokemypie** [comment]
Built from the aur, tagged where?

**Comment by nefthy** [comment]
@ibrokemypie could you provide the file?

**Comment by pgaskin** [comment]
I'm going to close this issue since it hasn't had a response for over 2 years. @ibrokemypie, feel free to reopen this issue if you still have this problem. It would be helpful to at least include the AUR build log.
